apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: 6c0f8cd6-ef5c-4692-879e-27618056f29c.k8s.civo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp
          servicePort: 8000